services:
  - type: web
    name: home-interior-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run db:generate && npm run db:deploy && npm run seed
    startCommand: npm run db:generate && npx prisma db push --accept-data-loss && npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://home-interior-backend.onrender.com
      - key: JWT_ACCESS_SECRET
        value: 4549201ef63a5517aa42bf414e7f7d4d
      - key: JWT_REFRESH_SECRET
        value: 7a29ae8f489a3252be841287f383543a
      - key: CLIENT_URL
        value: https://homy-comfy.netlify.app
      - key: SEED_ADMIN_EMAIL
        value: admin@chatgpt.com
      - key: SEED_ADMIN_PASSWORD
        value: admin123.
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_8g1kJfADurxe@ep-red-cake-aya2hje0-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
