/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Primary Luxury Backgrounds
        'warm-ivory': '#FAF8F4',
        'soft-cream': '#F5EFE8',
        'soft-beige': '#E6D8C9',

        // Luxury Accents
        'luxury-text': '#2A241F',
        'orange-accent': '#E89A43',
        'orange-hover': '#D88227',
        'soft-gold-divider': '#D6B27A',

        // Footer
        'footer-bg': '#1B1714',
        'footer-text': '#F7F4EF',

        // Semantic aliases for backwards compatibility
        cream: '#FAF8F4',
        beige: '#E6D8C9',
        espresso: '#2A241F',
        brown: '#6B4F3A',
        gold: '#D6B27A',
        bronze: '#E89A43',
        linen: '#F5EFE8',
        linenLight: '#FAF8F4',
        linenDark: '#E6D8C9',
        'footer-bg': '#1B1714',
        'footer-text': '#F7F4EF',
        'primary-bg': '#FAF8F4',
        'dark-luxury': '#2A241F',
        'warm-gold': '#D6B27A',
        champagne: '#E6D8C9',
        'luxury-beige': '#E6D8C9',
        white: '#FFFFFF',
        success: '#3F7A57',
        error: '#C62828',
        bg: '#FAF8F4',
        card: '#FFFFFF',
        primary: '#2A241F',
        secondary: '#E6D8C9',
        accent: '#E89A43',
        border: 'rgba(42,36,31,0.08)',
        borderSubtle: 'rgba(42,36,31,0.06)',
        shadow: 'rgba(42,36,31,0.06)',
        black: '#1B1714',
        textPrimary: '#2A241F',
        textSecondary: '#6B4F3A',
        footerBlack: '#1B1714',
        footerText: '#F7F4EF',
        darkBrown: '#2A241F',
        lightBeige: '#FAF8F4',
        bgPrimary: '#FAF8F4',
        bgSecondary: '#E6D8C9',
        textPrimaryDark: '#2A241F',
        cardCream: '#FFFFFF',
        sidebar: '#1B1714',
        accentOrange: '#E89A43',
        softOrange: '#E89A43',
        sand: '#E6D8C9',
        stone: '#6B4F3A',
        clay: '#E89A43',
        warm: '#D88227',
        warmBrown: '#6B4F3A',
        elegantOrange: '#E89A43',
        orange: '#E89A43',
        inkPrimary: '#2A241F',
        inkSecondary: '#6B4F3A',
        ink: '#2A241F',
        charcoal: '#1B1714',
        luxuryBeige: '#E6D8C9',
        luxuryBeigeLight: '#FAF8F4',
        luxuryBeigeSoft: '#FFFFFF',
        warmBeige: '#E6D8C9',
        warmBeigeLight: '#FAF8F4',
        warmBeigeSoft: '#FFFFFF',
        warning: '#E89A43',
        forest: '#2A241F',
        forestDark: '#1B1714',
        forestLight: '#2A241F',
        bronzeDark: '#D88227',
        bronzeLight: '#F0B060',
        creamDark: '#E6D8C9',
        creamLight: '#FFFFFF',
        charcoalLight: '#2A241F',
        maroon: '#6D3B3B',
        maroonDark: '#5A2E2E',
        maroonLight: '#8B4E4E',
        espressoDark: '#1B1714',
        espressoLight: '#3D2D25',
        beigeLight: '#F5EFE8',
        beigeDark: '#D4C4B0',
        brownLight: '#8B6F5A',
        brownDark: '#4D3A2D',
        goldDark: '#D88227',
        goldLight: '#F0B060',
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', '"Playfair Display"', 'Georgia', 'serif'],
        body: ['"Plus Jakarta Sans"', '"Inter"', 'system-ui', 'sans-serif'],
        sans: ['"Plus Jakarta Sans"', '"Inter"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        '3xs': ['0.6rem', { lineHeight: '0.9rem' }],
        'hero-desktop': ['5.25rem', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
        'hero-tablet': ['4rem', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
        'hero-mobile': ['2.75rem', { lineHeight: '1.05', letterSpacing: '-0.01em' }],
      },
      letterSpacing: {
        widest: '0.25em',
        wider: '0.18em',
        wide: '0.12em',
        luxury: '0.35em',
        'logo': '0.35em',
      },
      boxShadow: {
        soft: '0 4px 24px rgba(42,36,31,0.05)',
        card: '0 2px 16px rgba(42,36,31,0.04)',
        lift: '0 12px 40px rgba(42,36,31,0.08)',
        innerSoft: 'inset 0 2px 8px rgba(42,36,31,0.02)',
        glow: '0 0 20px rgba(232,154,67,0.1)',
        cardHover: '0 10px 30px rgba(0,0,0,0.03)',
        glass: '0 8px 32px rgba(27,23,20,0.12)',
        'glow-gold': '0 0 40px rgba(214,178,122,0.15)',
        'orange-glow': '0 20px 60px rgba(232,154,67,0.3)',
        'orange-glow-hover': '0 25px 80px rgba(232,154,67,0.4)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '3xl': '1.5rem',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        luxury: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInMenu: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideOutMenu: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        fadeInBackdrop: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        kenBurns: {
          '0%': { transform: 'scale(1) translate3d(0, 0, 0)' },
          '50%': { transform: 'scale(1.08) translate3d(-1.5%, -1%, 0)' },
          '100%': { transform: 'scale(1.12) translate3d(1.5%, 1%, 0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        shimmerGold: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        particleFloat: {
          '0%, 100%': { transform: 'translateY(0) translateX(0)', opacity: '0.3' },
          '25%': { transform: 'translateY(-20px) translateX(10px)', opacity: '0.6' },
          '50%': { transform: 'translateY(-10px) translateX(-5px)', opacity: '0.4' },
          '75%': { transform: 'translateY(-30px) translateX(15px)', opacity: '0.5' },
        },
        underlineSlide: {
          '0%': { width: '0%', left: '0%' },
          '50%': { width: '100%', left: '0%' },
          '100%': { width: '0%', left: '100%' },
        },
        dropdownFadeUp: {
          '0%': { opacity: '0', transform: 'translateY(10px) scale(0.98)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
      },
      animation: {
        fadeUp: 'fadeUp 0.5s ease-out forwards',
        shimmer: 'shimmer 1.8s infinite linear',
        fadeIn: 'fadeIn 0.25s ease-out forwards',
        scaleIn: 'scaleIn 0.25s ease-out forwards',
        slideInRight: 'slideInRight 0.3s ease-out forwards',
        slideInMenu: 'slideInMenu 0.3s ease-out forwards',
        slideOutMenu: 'slideOutMenu 0.3s ease-out forwards',
        fadeInBackdrop: 'fadeInBackdrop 0.3s ease-out forwards',
        kenBurns: 'kenBurns 20s ease-in-out infinite alternate',
        float: 'float 6s ease-in-out infinite',
        shimmerGold: 'shimmerGold 2s infinite linear',
        particleFloat: 'particleFloat 15s ease-in-out infinite',
        underlineSlide: 'underlineSlide 0.6s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        dropdownFadeUp: 'dropdownFadeUp 0.25s cubic-bezier(0.22, 1, 0.36, 1) forwards',
      },
      backgroundImage: {
        'luxury-gradient': 'linear-gradient(135deg, #FAF8F4 0%, #E6D8C9 100%)',
        'card-gradient': 'linear-gradient(180deg, #FFFFFF 0%, #FAF8F4 100%)',
        'hero-overlay': 'linear-gradient(90deg, rgba(250,248,244,0.92) 0%, rgba(250,248,244,0.80) 20%, rgba(250,248,244,0.50) 40%, rgba(250,248,244,0.15) 65%, rgba(250,248,244,0.00) 100%)',
        'gold-shimmer': 'linear-gradient(90deg, transparent, rgba(214,178,122,0.4), transparent)',
        'footer-glow': 'radial-gradient(ellipse at top center, rgba(214,178,122,0.06), transparent 60%)',
        'hero-radial': 'radial-gradient(ellipse at top right, rgba(232,154,67,0.12), transparent 50%)',
      },
    },
  },
  plugins: [],
}