/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-bg': '#FAF8F4',
        'dark-luxury': '#1F4D3A',
        'warm-gold': '#B88A5A',
        'champagne': '#E8D3BE',
        'luxury-beige': '#EDE7DE',
        'white': '#FFFFFF',
        'success': '#3F7A57',
        'error': '#C62828',
        'bg': '#FAF8F4',
        'card': '#FFFFFF',
        'primary': '#1F4D3A',
        'secondary': '#EDE7DE',
        'accent': '#B88A5A',
        'border': 'rgba(31,77,58,0.08)',
        'borderSubtle': 'rgba(31,77,58,0.06)',
        'shadow': 'rgba(31,77,58,0.06)',
        'black': '#000000',
        'textPrimary': '#2B2B2B',
        'textSecondary': '#5A5A5A',
        'footerBlack': '#1F4D3A',
        'footerText': '#FAF8F4',
        'darkBrown': '#1F4D3A',
        'lightBeige': '#FAF8F4',
        'cream': '#FAF8F4',
        'bgPrimary': '#FAF8F4',
        'bgSecondary': '#EDE7DE',
        'textPrimaryDark': '#2B2B2B',
        'cardCream': '#FFFFFF',
        'sidebar': '#1F4D3A',
        'accentOrange': '#B88A5A',
        'softOrange': '#B88A5A',
        'linen': '#EDE7DE',
        'sand': '#EDE7DE',
        'stone': '#5A5A5A',
        'clay': '#B88A5A',
        'warm': '#8B7355',
        'warmBrown': '#5A5A5A',
        'elegantOrange': '#B88A5A',
        'orange': '#B88A5A',
        'inkPrimary': '#2B2B2B',
        'inkSecondary': '#5A5A5A',
        'ink': '#2B2B2B',
        'charcoal': '#2B2B2B',
        'luxuryBeige': '#EDE7DE',
        'luxuryBeigeLight': '#FAF8F4',
        'luxuryBeigeSoft': '#FFFFFF',
        'warmBeige': '#EDE7DE',
        'warmBeigeLight': '#FAF8F4',
        'warmBeigeSoft': '#FFFFFF',
        'warning': '#B88A5A',
        'forest': '#1F4D3A',
        'forestDark': '#164030',
        'forestLight': '#2A6B4F',
        'bronze': '#B88A5A',
        'bronzeDark': '#9E754F',
        'bronzeLight': '#D4A87A',
        'creamDark': '#F0EBE3',
        'creamLight': '#FFFFFF',
        'charcoalLight': '#4A4A4A',
      },
      fontFamily: {
        display: ['"Playfair Display"', '"Playfair Display Fallback"', 'Georgia', 'serif'],
        body: ['"Inter"', '"Inter Fallback"', 'system-ui', 'sans-serif'],
        sans: ['"Inter"', '"Inter Fallback"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        '3xs': ['0.6rem', { lineHeight: '0.9rem' }],
      },
      letterSpacing: {
        widest: '0.25em',
        wider: '0.18em',
        wide: '0.12em',
      },
      boxShadow: {
        soft: '0 4px 24px rgba(31,77,58,0.05)',
        card: '0 2px 16px rgba(31,77,58,0.04)',
        lift: '0 12px 40px rgba(31,77,58,0.08)',
        innerSoft: 'inset 0 2px 8px rgba(31,77,58,0.02)',
        glow: '0 0 20px rgba(184,138,90,0.1)',
        cardHover: '0 10px 30px rgba(0,0,0,0.03)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
        '3xl': '1.5rem',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
        luxury: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInMenu: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideOutMenu: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        fadeInBackdrop: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        fadeUp: 'fadeUp 0.5s ease-out forwards',
        shimmer: 'shimmer 1.8s infinite linear',
        fadeIn: 'fadeIn 0.25s ease-out forwards',
        scaleIn: 'scaleIn 0.25s ease-out forwards',
        slideInRight: 'slideInRight 0.3s ease-out forwards',
        slideInMenu: 'slideInMenu 0.3s ease-out forwards',
        slideOutMenu: 'slideOutMenu 0.3s ease-out forwards',
        fadeInBackdrop: 'fadeInBackdrop 0.3s ease-out forwards',
      },
      backgroundImage: {
        'luxury-gradient': 'linear-gradient(135deg, #FAF8F4 0%, #EDE7DE 100%)',
        'card-gradient': 'linear-gradient(180deg, #FFFFFF 0%, #FAF8F4 100%)',
      },
    },
  },
  plugins: [],
}
